spring.application.name=team-task-manager

server.port=${PORT:8080}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/teamtaskmanager}

app.jwt.secret=${APP_JWT_SECRET:super-secret-key-that-should-be-replaced}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
